#!/bin/bash

AMI="$0"

while [ -h "$AMI" ]; do
  ls=$(ls -ld "$AMI")
  link=$(expr "$ls" : '.*-> \(.*\)$')
  if expr "$link" : '/.*' > /dev/null; then
    AMI="$link"
  else
    AMI=$(dirname "$AMI")/"$link"
  fi
done

# etched in the stone...
export AMI
export AMI_PROG=$(basename "$0")
export AMI_MDIR=$(dirname "$AMI")

AMI_CONF="$AMI_MDIR/etc/ami"
[ -f "$AMI_CONF" ] && . "$AMI_CONF" "$AMI_CONF" || { echo "$AMI_PROG: no $AMI_CONF config file found" >&2; exit 1; }

function settings() {
	for v in AMI AMI_PROG AMI_MDIR AMI_ETCD AMI_LIBD AMI_CMDP AMI_ROOT AMI_GITD AMI_SVND AMI_AURD; do
		echo "# $v = "$(eval echo \$$v);
	done
}

settings
export -f settings

function die() {
	echo "$2";
	exit $1;
}

function mkdirz() {
	for d in $GITD $SVND $AURD; do
		mkdir -p $d || die 1 "mkdirz init failure"
	done
}

cd "$ROOT" || die 1 "cd $ROOT failure"

function usage() {
	local prog=$(basename $0)
	echo "# '$prog cmds' to list available <cmd>s"
	die 3 "Usage: $prog [OPTS] <cmd> [OPTS] [ARGS]"
#	exit 3 #erm...
}

[ $# -eq 0 ] && usage

function run() {
	local cmd=$1
	shift
	bash "$CMDP/$cmd" "$@"
}

mkdirz

case $1 in
	cmds)
		ls -1 "$CMDP" ;;
	*)
		echo "## cmd: '$1' ##"
		run "$@" ;;
esac

echo "# ar<$@>gs #"
