#!/bin/bash

export AMI_VERSION=0.1.0
AMI="$0"

# "de-soft-link"
while [ -h "$AMI" ]; do
  ls=$(ls -ld "$AMI")
  link=$(expr "$ls" : '.*-> \(.*\)$')
  if expr "$link" : '/.*' > /dev/null; then
    AMI="$link"
  else
    AMI=$(dirname "$AMI")/"$link"
  fi
done

# etched in the stone...
export AMI
export AMI_PROG=$(basename "$0")
export AMI_MDIR=$(dirname "$AMI")

# try hard to do the right thing[tm]
[ "$AMI_MDIR" = "." ] && AMI_MDIR=$(pwd);
[[ "$AMI_MDIR" =~ ^/ ]] || AMI_MDIR=$(cd "$AMI_MDIR" && pwd);

# load library
AMI_LIBF="$AMI_MDIR/lib/ami"
[ -f "$AMI_LIBF" ] && . "$AMI_LIBF" "$AMI_LIBF" || { echo "$AMI_PROG: no $AMI_LIBF lib file found" >&2; exit 1; }
# it loads config so in practice 'load lib ami' alone in cmds should be ok

export AMI_CWD=$(pwd)
# not sure about that...
[ -n "$AMI_ROOT" ] || die "AMI_ROOT not set.";
cd "$AMI_ROOT" || die "cd $AMI_ROOT failure.";

# bail if nothing to do...
[ $# -eq 0 ] && usage;

# main()
settings
debug "main() args: '$@'.";
debug "main() cmd: '$1'.";
#die;
case $1 in
	cmds)
		cmds ;;
	init)
		shift
		runcmd init $* ;;
	*)
		runcmd init
		runcmd "$@" ;;
esac

ret=$?

debug "main() pwd '$(pwd)'.";

exit $ret;
