#!/bin/bash

PRGN="$0"

while [ -h "$PRGN" ]; do
  ls=$(ls -ld "$PRGN")
  link=$(expr "$ls" : '.*-> \(.*\)$')
  if expr "$link" : '/.*' > /dev/null; then
    PRGN="$link"
  else
    PRGN=$(dirname "$PRGN")/"$link"
  fi
done

export PRGN
export DIRN=$(dirname "$PRGN")
CMDP="$DIRN/bin"
export ROOT=$(dirname "$DIRN")
#R00T=$(dirname "$DIRN/..")
export GITD="$ROOT/git"
export SVND="$ROOT/svn"
export AURD="$ROOT/aur"

function settings() {
	for v in PRGN DIRN CMDP ROOT GITD SVND AURD; do
		echo "# $v = "$(eval echo \$$v);
	done
}

settings
export -f settings

function die() {
	echo "$2";
	exit $1;
}

function mkdirz() {
	for d in $GITD $SVND $AURD; do
		mkdir -p $d || die 1 "mkdirz init failure"
	done
}

cd "$ROOT" || die 1 "cd $ROOT failure"

function usage() {
	local prog=$(basename $0)
	echo "# '$prog cmds' to list available <cmd>s"
	die 3 "Usage: $prog [OPTS] <cmd> [OPTS] [ARGS]"
#	exit 3 #erm...
}

[ $# -eq 0 ] && usage

function run() {
	local cmd=$1
	shift
	bash "$CMDP/$cmd" "$@"
}

mkdirz

case $1 in
	cmds)
		ls -1 "$CMDP" ;;
	*)
		echo "## cmd: '$1' ##"
		run "$@" ;;
esac

echo "# ar<$@>gs #"
